FROM ubuntu
WORKDIR /root
RUN apt-get update && apt-get install -y openssh-server
RUN apt-get update && apt-get install nano && apt-get install -y openjdk-8-jdk
RUN mkdir bigdata
RUN wget https://dlcdn.apache.org/hadoop/common/hadoop-3.3.4/hadoop-3.3.4.tar.gz
RUN tar -C /root/bigdata/ -xvzf hadoop-3.3.4.tar.gz
RUN mkdir /root/bigdata/hadoop-3.3.4/hdfs
RUN mkdir /root/bigdata/hadoop-3.3.4/hdfs/data
RUN mkdir /root/bigdata/hadoop-3.3.4/hdfs/name
COPY /hadoop_config/* /root/bigdata/hadoop-3.3.4/etc/hadoop
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
ENV HADOOP_HOME=/root/bigdata/hadoop-3.3.4
ENV HADOOP_USER_NAME=hadoop
ENV PATH=$PATH:$HADOOP_HOME/bin:$JAVA_HOME/bin
RUN service ssh start
RUN ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N "" && \
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
EXPOSE 22
CMD [ "sh", "/etc/init.d/ssh", "start"]
RUN bigdata/hadoop-3.3.4/bin/hdfs namenode -format
RUN bigdata/hadoop-3.3.4/sbin/start-dfs.sh
ENTRYPOINT service ssh restart && bash
